WHEELS_PORT: "/dev/ttyACM1" 
WHEELS_BAUDRATE: 115200
fps: 30
CONE_DETECTION_MODEL_PATH: "/home/adastra/ws/IRC-2025/Test/IRC-AUTONOMOUS/src/cone.pt"
CONE_CONFIDENCE_THRESHOLD: 1.0
ARROW_DETECTION_MODEL_PATH: "/home/adastra/ws/IRC-2025/Test/IRC-AUTONOMOUS/src/arrow-small.pt"
LIMIT_X: 25
PROXIMITY_LIMIT: 1.0
LEFT_X: 600
RIGHT_X: 680
THRESHOLD_DEGREE: 1
PIXHAWK_CONNECTION_PORT: "/dev/ttyACM0"
PIXHAWK_BAUDRATE: 115200
